#!/bin/sh
# Script for running serial program, diffuse.

#PBS -l walltime=72:00:00
#PBS -l mem=21000mb
#PBS -r n

ulimit -S -v 20000000

gcm=BNU-ESM
rcp=rcp26
run=r1i1p1


cd /home/ssobie/stat.downscaling/code/QPQM/BCCA/
echo "Current working directory is `pwd`"

/global/software/R-3.0.2/bin/R CMD BATCH "--args gcm='${gcm}' rcp='${rcp}' run='${run}'" BCCA.2.aggregate_obs.R "./out.files/bcca.2.agg.${gcm}.${rcp}.${run}.out" 
echo "Program BCCA 2 Aggregate finished with exit code $? at: `date`"

