#!/bin/sh
# Script for running serial program, diffuse.

#PBS -l walltime=72:00:00
#PBS -l mem=10000mb
#PBS -r n

ulimit -S -v 9000000

gcm=BNU-ESM
rcp=rcp26
run=r1i1p1

cd /home/ssobie/stat.downscaling/code/QPQM/BCCA/
echo "Current working directory is `pwd`"

/global/software/R-3.0.2/bin/R CMD BATCH "--args gcm='${gcm}' rcp='${rcp}' run='${run}'" BCCA.1.setup_file.R "./out.files/bcca.1.setup.${gcm}.${rcp}.${run}.out"
echo "Program BCCA 1 Set up finished with exit code $? at: `date`"

