#!/bin/sh
# Script for running serial program, diffuse.

#PBS -l walltime=2:00:00
#PBS -l mem=10000mb
#PBS -r n

ulimit -S -v 9000000

gcm=BNU-ESM
rcp=rcp26
run=r1i1p1

pushd $PBS_O_WORKDIR
echo "Current working directory is `pwd`"

module load R
R CMD BATCH "--args gcm='${gcm}' rcp='${rcp}' run='${run}'" BCCA.R "$HOME/ClimDown/output/bcca.${gcm}.${rcp}.${run}.out"
echo "Program BCCA Set up finished with exit code $? at: `date`"

